TOPDIR=./../..

TARGET=pokaftp

LIBPATH=$(TOPDIR)/lib
EXEPATH=$(TOPDIR)/bin


CFLAGS= -g  -I$(TOPDIR)/include/ 
LDFLAGS+= -L$(TOPDIR)/lib -lpokalog  -lcommon -lpthread -lrt -lm

include $(TOPDIR)/cfg/Makefile.mk