TOPDIR=./../..

#TARGET=myftp
LIB=libpokaftp.a

exclude_files=testftp.c

INCPATH=$(TOPDIR)/include/
LIBPATH=$(TOPDIR)/lib
CFLAGS+= -I$(INCPATH)

#LDFLAGS= -L$(TOPDIR)/lib

include $(TOPDIR)/cfg/Makefile.mk