TOPDIR=./../../..

LIB=libdboracle.a

INCPATH=$(TOPDIR)/include/
LIBPATH=$(TOPDIR)/lib
CFLAGS= -I$(INCPATH) -l

DBINCLUD=$(INCPATH)
DBTYPE=oracle
include $(TOPDIR)/cfg/Makefile.db

include $(TOPDIR)/cfg/Makefile.mk