TOPDIR=./../..

TARGET=pokadaemon

SUBTARGET=pftpdaemon

LIBPATH=$(TOPDIR)/lib
EXEPATH=$(TOPDIR)/bin

CFLAGS= -g  -I$(TOPDIR)/include/ 
LDFLAGS+= -L$(TOPDIR)/lib -lpokalog -lcommon -lpthread -lrt

include $(TOPDIR)/cfg/Makefile.mk


