

------------------------------------------------
-- DDL STATEMENTS FOR TABLE "BUSINESSLIST_ATM"
------------------------------------------------

CREATE TABLE "DOUBTMONEYDATA"  (
		  "PERCODE" VARCHAR(24 OCTETS) , 
		  "COLTIME" TIMESTAMP , 
		  "MON" VARCHAR(12 OCTETS) , 
		  "MONTYPE" CHAR(3 OCTETS) , 
		  "MONVAL" CHAR(3 OCTETS) , 
		  "MONVER" CHAR(4 OCTETS) , 
		  "TRUEFLAG" CHAR(1 OCTETS) , 
		  "OPERATORID" VARCHAR(20 OCTETS) , 
		  "OPERDATE" TIMESTAMP , 
		  "BUNDLEID" VARCHAR(24 OCTETS) , 
		  "PACKAGEID" VARCHAR(24 OCTETS) , 
		  "CHECKER" VARCHAR(20 OCTETS) , 
		  "IMAGEPATH" VARCHAR(256 OCTETS) , 
		  "BUSINESSTYPE" VARCHAR(4 OCTETS) , 
		  "MONBOXID" VARCHAR(24 OCTETS) , 
		  "ATMID" VARCHAR(24 OCTETS) , 
		  "ADDMONOPERATOR" VARCHAR(20 OCTETS) , 
		  "ADDMONCHECKER" VARCHAR(20 OCTETS) , 
		  "BANKNO" VARCHAR(20 OCTETS) , 
		  "AGENCYNO" VARCHAR(20 OCTETS) , 
		  "FILENAME" VARCHAR(60 OCTETS) , 
		  "CLASSID" VARCHAR(2 OCTETS) )   
		 IN "USERSPACE1"  
		 ORGANIZE BY ROW; 
		 
CREATE TABLE "TRS_BUNDLE" (
  "ORDERID" VARCHAR(30) DEFAULT NULL,
  "BANKID" VARCHAR(20) DEFAULT NULL,
  "NETID" VARCHAR(20) DEFAULT NULL,
  "BAGCODE" VARCHAR(30) DEFAULT NULL,
  "BUNDLECODE" VARCHAR(30) DEFAULT NULL,
  "MONEYID" VARCHAR(2) DEFAULT NULL,
  "MONEYBAD" VARCHAR(1) DEFAULT NULL,
  "BAGID" VARCHAR(20) DEFAULT NULL,
  "CHECKID" VARCHAR(20) DEFAULT NULL,
  "BUNDLEMONEY" DOUBLE DEFAULT NULL,
  "BUNDLEDATE" TIMESTAMP DEFAULT NULL,
  "ISBAG" INTEGER DEFAULT NULL
) IN "USERSPACE1";

CREATE TABLE "TMP_BUNDLES" (
  "BUNDLECODE" VARCHAR(20) NOT NULL,
  "ORDERID" VARCHAR(20) NOT NULL,
  "PROVID" VARCHAR(2) NOT NULL,
  "UNITID" VARCHAR(4) NOT NULL,
  "AREACODE" VARCHAR(10) DEFAULT NULL,
  "BAGCODE" VARCHAR(20) DEFAULT NULL,
  "BAGID" VARCHAR(8) DEFAULT NULL,
  "BAGSTATE" VARCHAR(255) DEFAULT NULL,
  "BUNDLEKIND" INTEGER DEFAULT NULL,
  "BUNDLEMONEY" DOUBLE DEFAULT NULL,
  "BUNDLESTATE" INTEGER DEFAULT NULL,
  "CHECKID" VARCHAR(8) DEFAULT NULL,
  "CREATEDATE" TIMESTAMP DEFAULT NULL,
  "CURRENCYID" VARCHAR(2) DEFAULT NULL,
  "CURRENCYKIND" INTEGER DEFAULT NULL,
  "EMPID" VARCHAR(8) DEFAULT NULL,
  "ISOK" INTEGER DEFAULT NULL,
  "MACHID" VARCHAR(12) DEFAULT NULL,
  "MSG" VARCHAR(50) DEFAULT NULL,
  "PRINTCOUNT" INTEGER DEFAULT NULL,
  "SCANID" VARCHAR(2) DEFAULT NULL,
  "STATE" INTEGER DEFAULT NULL,
  "TMPBUNDLECODE" VARCHAR(24) DEFAULT NULL
) IN "USERSPACE1";


CREATE TABLE "TRS_ORDER"  (
		  "FID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (  
		    START WITH +1  
		    INCREMENT BY +1  
		    MINVALUE +1  
		    MAXVALUE +2147483647  
		    NO CYCLE  
		    NO CACHE  
		    NO ORDER ) , 
		  "BANKID" VARCHAR(20) , 
		  "ORDERID" VARCHAR(50) , 
		  "ORDERTYPE" INTEGER , 
		  "INSERTDATE" TIMESTAMP WITH DEFAULT CURRENT TIMESTAMP , 
		  "STATE" INTEGER WITH DEFAULT 0 , 
		  "FINISHDATE" TIMESTAMP )   
		 IN "USERSPACE1"  
		 ORGANIZE BY ROW; 
		 
CREATE TABLE "T_ORDERINFO"  (
		  "FID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (  
		    START WITH +1  
		    INCREMENT BY +1  
		    MINVALUE +1  
		    MAXVALUE +2147483647  
		    NO CYCLE  
		    NO CACHE  
		    NO ORDER ) , 
		  "BANKID" VARCHAR(20) , 
		  "ORDERID" VARCHAR(50) , 
		  "ORDERTYPE" INTEGER , 
		  "INSERTDATE" TIMESTAMP WITH DEFAULT CURRENT TIMESTAMP , 
		  "STATE" INTEGER WITH DEFAULT 0 , 
		  "FINISHDATE" TIMESTAMP )   
		 IN "USERSPACE1"  
		 ORGANIZE BY ROW; 
		 

CREATE TABLE "BUSINESSLIST_ATM"  (
			"ID"           VARCHAR(30) NOT NULL,
			"BANKNO"       VARCHAR(20),
			"NETNO"        VARCHAR(20),
			"PERCODE"      VARCHAR(30),
			"ACCOUNTNO"    VARCHAR(30),
			"BUSINESSDATE" DATE,
			"BUSINESSID"   VARCHAR(50),
			"MONEYTOTAL"   DECIMAL(18,2),
			"INOROUT"      CHAR(1),
			"COREID"       VARCHAR(30),
			"REMARK"       VARCHAR(200),
			"INSERTDATE"   TIMESTAMP WITH DEFAULT CURRENT TIMESTAMP )   
		 IN "USERSPACE1" ; 


-- DDL STATEMENTS FOR PRIMARY KEY ON TABLE "BUSINESSLIST_ATM"

ALTER TABLE "BUSINESSLIST_ATM" 
	ADD CONSTRAINT "IX_BUSINESSLIST_ATM_ID" PRIMARY KEY
		("ID");

CREATE INDEX "IX_BUSINESSLIST_ATM_ACCOUNTNO" ON "BUSINESSLIST_ATM" 
		("ACCOUNTNO" ASC)
		ALLOW REVERSE SCANS;

CREATE INDEX "IX_BUSINESSLIST_ATM_COREID" ON "BUSINESSLIST_ATM" 
		("COREID" ASC)
		ALLOW REVERSE SCANS;

CREATE INDEX "IX_BUSINESSLIST_ATM_INSERDATE" ON "BUSINESSLIST_ATM" 
		("INSERTDATE" ASC)
		ALLOW REVERSE SCANS;

CREATE INDEX "IX_BUSINESSLIST_ATM_NETNO" ON "BUSINESSLIST_ATM" 
		("NETNO" ASC)
		ALLOW REVERSE SCANS;



------------------------------------------------
-- DDL STATEMENTS FOR TABLE "BUSINESSLIST_CORE"
------------------------------------------------
 

CREATE TABLE "BUSINESSLIST_CORE"  (
			"ID"           VARCHAR(50) NOT NULL,
			"BANKNO"       VARCHAR(20),
			"NETNO"        VARCHAR(20),
			"USERID"       VARCHAR(8),
			"BUSINESSDATE" DATE,
			"BUSINESSID"   VARCHAR(50),
			"MONEYTOTAL"   DECIMAL(18,2),
			"INOROUT"      CHAR(1),
			"ACCOUNTNO"    VARCHAR(30),
			"ACCOUNTNAME"  VARCHAR(30),
			"ACCOUNTTYPE"  VARCHAR(2),
			"PUBORPRI"     CHAR(1),
			"CHANNEL"      CHAR(1),
			"REMARK"       VARCHAR(200),
			"INSERTDATE"   TIMESTAMP WITH DEFAULT CURRENT TIMESTAMP )   
		 IN "USERSPACE1" ; 


-- DDL STATEMENTS FOR PRIMARY KEY ON TABLE "BUSINESSLIST_CORE"

ALTER TABLE "BUSINESSLIST_CORE" 
	ADD CONSTRAINT "IX_BUSINESSLIST_CORE_ID" PRIMARY KEY
		("ID");

CREATE INDEX "IX_BT_CORE_BUSINESSDATE" ON "BUSINESSLIST_CORE" 
		("BUSINESSDATE" ASC)
		ALLOW REVERSE SCANS;

CREATE INDEX "IX_BT_CORE_BUSINESSID" ON "BUSINESSLIST_CORE" 
		("BUSINESSID" ASC)
		ALLOW REVERSE SCANS;

CREATE INDEX "IX_BUSINESSLIST_CORE_ACCOUNTNO" ON "BUSINESSLIST_CORE" 
		("ACCOUNTNO" ASC)
		ALLOW REVERSE SCANS;

CREATE INDEX "IX_BUSINESSLIST_CORE_INSERDATE" ON "BUSINESSLIST_CORE" 
		("INSERTDATE" ASC)
		ALLOW REVERSE SCANS;

CREATE INDEX "IX_BUSINESSLIST_CORE_NETNO" ON "BUSINESSLIST_CORE" 
		("NETNO" ASC)
		ALLOW REVERSE SCANS;



------------------------------------------------
-- DDL STATEMENTS FOR TABLE "BUSINESSLIST_DETAIL"
------------------------------------------------
 

CREATE TABLE "BUSINESSLIST_DETAIL"  (
            "ID"         VARCHAR(50) NOT NULL,
            "MONVAL"     DECIMAL(8,2) NOT NULL,
            "RECORDS"    BIGINT,
            "INSERTDATE" TIMESTAMP WITH DEFAULT CURRENT TIMESTAMP )   
		 IN "USERSPACE1" ; 


-- DDL STATEMENTS FOR PRIMARY KEY ON TABLE "BUSINESSLIST_DETAIL"

ALTER TABLE "BUSINESSLIST_DETAIL" 
	ADD CONSTRAINT "IX_BUSINESSLIST_DETAIL_ID" PRIMARY KEY
		("ID", "MONVAL");

CREATE INDEX "IX_BT_DETAIL_INSERDATE" ON "BUSINESSLIST_DETAIL" 
		("INSERTDATE" ASC)
		ALLOW REVERSE SCANS;



------------------------------------------------
-- DDL STATEMENTS FOR TABLE "DATECUT"
------------------------------------------------
 

CREATE TABLE "DATECUT"  (
            "ID"       INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (  
		    START WITH +1  
		    INCREMENT BY +1  
		    MINVALUE +1  
		    MAXVALUE +2147483647  
		    NO CYCLE  
		    NO CACHE  
		    NO ORDER ) ,
            "LASTDATE" VARCHAR(20),
            "CURDATE"  VARCHAR(20),
            "STATUS"   CHAR(1),
            "CUTTIME"  INTEGER,
            "ENDTIME"  INTEGER )   
		 IN "USERSPACE1" ; 


-- DDL STATEMENTS FOR PRIMARY KEY ON TABLE "DATECUT"

ALTER TABLE "DATECUT" 
	ADD CONSTRAINT "IX_DATECUT_ID" PRIMARY KEY
		("ID");



------------------------------------------------
-- DDL STATEMENTS FOR TABLE "MONEYDATA_ATM"
------------------------------------------------
 

CREATE TABLE "MONEYDATA_ATM"  (
            "ID"           VARCHAR(30) NOT NULL,
            "PERCODE"      VARCHAR(24),
            "COLTIME"      DATE,
            "MON"          VARCHAR(20),
            "MONTYPE"      CHAR(3),
            "MONVAL"       DECIMAL(8,2),
            "MONVER"       CHAR(4),
            "TRUEFLAG"     CHAR(1),
            "QUANLITY"     CHAR(2),
            "OPERDATE"     DATE,
            "IMAGEPATH"    VARCHAR(256),
            "BUSINESSTYPE" VARCHAR(4),
            "BANKNO"       VARCHAR(20),
            "AGENCYNO"     VARCHAR(20),
            "BUSINESSID"   VARCHAR(30),
            "RESERVE1"     VARCHAR(50),
            "RESERVE2"     VARCHAR(50) )   
		 IN "USERSPACE1" ; 


-- DDL STATEMENTS FOR PRIMARY KEY ON TABLE "MONEYDATA_ATM"

ALTER TABLE "MONEYDATA_ATM" 
	ADD CONSTRAINT "IX_MONEYDATA_ATM_ID" PRIMARY KEY
		("ID");

CREATE INDEX "IX_MONEYDATA_ATM_BUSINESSID" ON "MONEYDATA_ATM" 
		("BUSINESSID" ASC)
		ALLOW REVERSE SCANS;

CREATE INDEX "IX_MONEYDATA_ATM_COLTIME" ON "MONEYDATA_ATM" 
		("COLTIME" ASC)
		ALLOW REVERSE SCANS;

CREATE INDEX "IX_MONEYDATA_ATM_MON" ON "MONEYDATA_ATM" 
		("MON" ASC)
		ALLOW REVERSE SCANS;

CREATE INDEX "IX_MONEYDATA_ATM_OPERDATE" ON "MONEYDATA_ATM" 
		("OPERDATE" ASC)
		ALLOW REVERSE SCANS;



------------------------------------------------
-- DDL STATEMENTS FOR TABLE "ROUTE"
------------------------------------------------
 

CREATE TABLE "ROUTE"  (
            "ID"          VARCHAR(30) NOT NULL,
            "TARGETBANK"  VARCHAR(20),
            "FORWARDBANK" VARCHAR(20),
            "IPADDR"      VARCHAR(20),
            "PORT_"       VARCHAR(8),
            "LOCALDIR"    VARCHAR(100),
            "REMOTEDIR"   VARCHAR(100),
            "SERVICECODE" VARCHAR(20),
            "LASTDATE"    VARCHAR(20),
            "STARTTIME"   INTEGER,
            "INTER_VAL"   VARCHAR(32),
            "USER_"       VARCHAR(20),
            "PASSWORD_"   VARCHAR(20),
            "TYPE_"       SMALLINT,
            "STATUS_"     CHAR(1),
            "MODEL_"      INTEGER DEFAULT 0 )   
		 IN "USERSPACE1" ; 


-- DDL STATEMENTS FOR PRIMARY KEY ON TABLE "ROUTE"

ALTER TABLE "ROUTE" 
	ADD CONSTRAINT "IX_ROUTE_1_ID" PRIMARY KEY
		("ID");



------------------------------------------------
-- DDL STATEMENTS FOR TABLE "SKJL"
------------------------------------------------
 

CREATE TABLE "SKJL"  (
            "ID"              VARCHAR(30) NOT NULL,
            "BANKNO"          VARCHAR(20),
            "NETNO"           VARCHAR(20),
            "USERID"          VARCHAR(8),
            "PERCODE"         VARCHAR(30),
            "BUSINESSDATE"    DATE,
            "ACCOUNTNO"       VARCHAR(30),
            "INSERTDATE"      DATE )   
		 IN "USERSPACE1" ; 


-- DDL STATEMENTS FOR PRIMARY KEY ON TABLE "SKJL"

ALTER TABLE "SKJL" 
	ADD CONSTRAINT "IX_SKJL_1_ID" PRIMARY KEY
		("ID");

CREATE INDEX "IX_SKJL_BUSINESSDATE" ON "SKJL" 
		("BUSINESSDATE" ASC)
		ALLOW REVERSE SCANS;

CREATE INDEX "IX_SKJL_ACCOUNTNO" ON "SKJL" 
		("ACCOUNTNO" ASC)
		ALLOW REVERSE SCANS;



------------------------------------------------
-- DDL STATEMENTS FOR TABLE "KUNFILES"
------------------------------------------------
 

CREATE TABLE "KUNFILES"  (
            "BUNDLECODE"  VARCHAR(30),
            "TYPE"        VARCHAR(8),
            "PATH"        VARCHAR(256),
            "NAME"        VARCHAR(100),
            "INSERTDATE"  DATE )   
		 IN "USERSPACE1" ; 



-- DDL STATEMENTS FOR PRIMARY KEY ON TABLE "KUNFILES"

ALTER TABLE "KUNFILES" 
	ADD CONSTRAINT "KEY_KUNFILES" PRIMARY KEY
		("BUNDLECODE", "TYPE");

CREATE INDEX "IX_KUNFILES_IE" ON "KUNFILES" 
		("INSERTDATE" ASC)
		ALLOW REVERSE SCANS;



------------------------------------------------
-- DDL STATEMENTS FOR TABLE "SEARCHFSNBK"
------------------------------------------------
 

CREATE TABLE "SEARCHFSNBK"  (
            "ID"          VARCHAR(30) NOT NULL,
            "BUNDLECODE"  VARCHAR(30),
            "ORDERID"     VARCHAR(30),
            "TYPE"        VARCHAR(8) )   
		 IN "USERSPACE1" ; 


-- DDL STATEMENTS FOR PRIMARY KEY ON TABLE "SEARCHFSNBK"

ALTER TABLE "SEARCHFSNBK" 
	ADD CONSTRAINT "IX_SEARCHFSNBK_ID" PRIMARY KEY
		("ID");



------------------------------------------------
-- DDL STATEMENTS FOR TABLE "ROUTERULE"
------------------------------------------------
 

CREATE TABLE "ROUTERULE"  (
            "ID"         VARCHAR(30) NOT NULL,
            "ROUTEID"    VARCHAR(30),
            "FILEEXTEND" VARCHAR(10) )   
		 IN "USERSPACE1" ; 


-- DDL STATEMENTS FOR PRIMARY KEY ON TABLE "ROUTERULE"

ALTER TABLE "ROUTERULE" 
	ADD CONSTRAINT "IX_ROUTERULE_ID" PRIMARY KEY
		("ID");



ALTER TABLE BUNDLEINFO ADD COLUMN ID VARCHAR(30); 

ALTER TABLE MONBOXADDMON ADD COLUMN ID VARCHAR(30); 

ALTER TABLE MONEYDATA ADD COLUMN PACKAGEID VARCHAR(24);

ALTER TABLE PERINFO ADD COLUMN TERMINALNO VARCHAR(30);

ALTER TABLE TRS_ORDER ADD COLUMN SENDSTATE VARCHAR(2);
