CREATE TABLE IF NOT EXISTS `BUSINESSLIST_ATM` (
  `ID` bigint(30) NOT NULL AUTO_INCREMENT,
  `BANKNO` varchar(20) DEFAULT NULL,
  `NETNO` varchar(20) DEFAULT NULL,
  `PERCODE` varchar(30) DEFAULT NULL,
  `ACCOUNTNO` varchar(30) DEFAULT NULL,
  `BUSINESSDATE` timestamp NULL DEFAULT NULL,
  `BUSINESSID` varchar(50) DEFAULT NULL,
  `MONEYTOTAL` decimal(18,2) DEFAULT NULL,
  `INOROUT` char(1) DEFAULT NULL,
  `COREID` varchar(30) DEFAULT NULL,
  `REMARK` varchar(200) DEFAULT NULL,
  `INSERTDATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `IX_BUSINESSLIST_ATM_BUSINESSDATE` (`BUSINESSDATE`) USING BTREE,
  KEY `IX_BUSINESSLIST_ATM_ACCOUNTNO` (`ACCOUNTNO`) USING BTREE,
  KEY `IX_BUSINESSLIST_ATM_NETNO` (`NETNO`) USING BTREE,
  KEY `IX_BUSINESSLIST_ATM_COREID` (`COREID`) USING BTREE,
  KEY `IX_BUSINESSLIST_ATM_INSERDATE` (`INSERTDATE`) USING BTREE
) ENGINE=MyISAM AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

ALTER TABLE `BUSINESSLIST_ATM` ADD COLUMN       `ID` bigint(30) NOT NULL AUTO_INCREMENT;               
ALTER TABLE `BUSINESSLIST_ATM` ADD COLUMN       `BANKNO` varchar(20) DEFAULT NULL;                     
ALTER TABLE `BUSINESSLIST_ATM` ADD COLUMN       `NETNO` varchar(20) DEFAULT NULL;                      
ALTER TABLE `BUSINESSLIST_ATM` ADD COLUMN       `PERCODE` varchar(30) DEFAULT NULL;                    
ALTER TABLE `BUSINESSLIST_ATM` ADD COLUMN       `ACCOUNTNO` varchar(30) DEFAULT NULL;                  
ALTER TABLE `BUSINESSLIST_ATM` ADD COLUMN       `BUSINESSDATE` timestamp NULL DEFAULT NULL;            
ALTER TABLE `BUSINESSLIST_ATM` ADD COLUMN       `BUSINESSID` varchar(50) DEFAULT NULL;                 
ALTER TABLE `BUSINESSLIST_ATM` ADD COLUMN       `MONEYTOTAL` decimal(18,2) DEFAULT NULL;               
ALTER TABLE `BUSINESSLIST_ATM` ADD COLUMN       `INOROUT` char(1) DEFAULT NULL;                        
ALTER TABLE `BUSINESSLIST_ATM` ADD COLUMN       `COREID` varchar(30) DEFAULT NULL;                     
ALTER TABLE `BUSINESSLIST_ATM` ADD COLUMN       `REMARK` varchar(200) DEFAULT NULL;                    
ALTER TABLE `BUSINESSLIST_ATM` ADD COLUMN       `INSERTDATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP; 

CREATE TABLE  IF NOT EXISTS `BUSINESSLIST_CORE` (
  `ID` varchar(50) NOT NULL,
  `BANKNO` varchar(20) DEFAULT NULL,
  `NETNO` varchar(20) DEFAULT NULL,
  `USERID` varchar(8) DEFAULT NULL,
  `BUSINESSDATE` timestamp NULL DEFAULT NULL,
  `BUSINESSID` varchar(50) DEFAULT NULL,
  `MONEYTOTAL` decimal(18,2) DEFAULT NULL,
  `INOROUT` char(1) DEFAULT NULL,
  `ACCOUNTNO` varchar(30) DEFAULT NULL,
  `ACCOUNTNAME` varchar(30) DEFAULT NULL,
  `ACCOUNTTYPE` varchar(2) DEFAULT NULL,
  `PUBORPRI` char(1) DEFAULT NULL,
  `CHANNEL` char(1) DEFAULT NULL,
  `REMARK` varchar(200) DEFAULT NULL,
  `INSERTDATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `IX_BUSINESSLIST_CORE_NETNO` (`NETNO`) USING BTREE,
  KEY `IX_BUSINESSLIST_CORE_BUSINESSDATE` (`BUSINESSDATE`),
  KEY `IX_BUSINESSLIST_CORE_ACCOUNTNO` (`ACCOUNTNO`) USING BTREE,
  KEY `IX_BUSINESSLIST_CORE_BUSINESSID` (`BUSINESSID`) USING BTREE,
  KEY `IX_BUSINESSLIST_CORE_INSERDATE` (`INSERTDATE`) USING BTREE
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

ALTER TABLE `BUSINESSLIST_CORE` ADD COLUMN     `ID` varchar(50) NOT NULL;                              
ALTER TABLE `BUSINESSLIST_CORE` ADD COLUMN     `BANKNO` varchar(20) DEFAULT NULL;                      
ALTER TABLE `BUSINESSLIST_CORE` ADD COLUMN     `NETNO` varchar(20) DEFAULT NULL;                       
ALTER TABLE `BUSINESSLIST_CORE` ADD COLUMN     `USERID` varchar(8) DEFAULT NULL;                       
ALTER TABLE `BUSINESSLIST_CORE` ADD COLUMN     `BUSINESSDATE` timestamp NULL DEFAULT NULL;             
ALTER TABLE `BUSINESSLIST_CORE` ADD COLUMN     `BUSINESSID` varchar(50) DEFAULT NULL;                  
ALTER TABLE `BUSINESSLIST_CORE` ADD COLUMN     `MONEYTOTAL` decimal(18,2) DEFAULT NULL;                
ALTER TABLE `BUSINESSLIST_CORE` ADD COLUMN     `INOROUT` char(1) DEFAULT NULL;                         
ALTER TABLE `BUSINESSLIST_CORE` ADD COLUMN     `ACCOUNTNO` varchar(30) DEFAULT NULL;                   
ALTER TABLE `BUSINESSLIST_CORE` ADD COLUMN     `ACCOUNTNAME` varchar(30) DEFAULT NULL;                 
ALTER TABLE `BUSINESSLIST_CORE` ADD COLUMN     `ACCOUNTTYPE` varchar(2) DEFAULT NULL;                  
ALTER TABLE `BUSINESSLIST_CORE` ADD COLUMN     `PUBORPRI` char(1) DEFAULT NULL;                        
ALTER TABLE `BUSINESSLIST_CORE` ADD COLUMN     `CHANNEL` char(1) DEFAULT NULL;                         
ALTER TABLE `BUSINESSLIST_CORE` ADD COLUMN     `REMARK` varchar(200) DEFAULT NULL;                     
ALTER TABLE `BUSINESSLIST_CORE` ADD COLUMN     `INSERTDATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP;  

CREATE TABLE  IF NOT EXISTS `BUSINESSLIST_DETAIL` (
  `ID` varchar(50) NOT NULL,
  `MONVAL` decimal(8,2) NOT NULL,
  `RECORDS` int(11) NOT NULL,
  `INSERTDATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`,`MONVAL`),
  KEY `IX_BUSINESSLIST_DETAIL_INSERDATE` (`INSERTDATE`) USING BTREE
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

ALTER TABLE `BUSINESSLIST_DETAIL` ADD COLUMN    `ID` varchar(50) NOT NULL;                            
ALTER TABLE `BUSINESSLIST_DETAIL` ADD COLUMN    `MONVAL` decimal(8,2) NOT NULL;                       
ALTER TABLE `BUSINESSLIST_DETAIL` ADD COLUMN    `RECORDS` int(11) NOT NULL;                           
ALTER TABLE `BUSINESSLIST_DETAIL` ADD COLUMN    `INSERTDATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP;

CREATE TABLE  IF NOT EXISTS `MONEYDATA_ATM` (
  `ID` smallint(6) NOT NULL AUTO_INCREMENT,
  `PERCODE` varchar(24) DEFAULT NULL,
  `COLTIME` datetime DEFAULT NULL,
  `MON` varchar(20) DEFAULT NULL,
  `MONTYPE` char(3) DEFAULT NULL,
  `MONVAL` decimal(8,2) DEFAULT NULL,
  `MONVER` char(4) DEFAULT NULL,
  `TRUEFLAG` char(1) DEFAULT NULL,
  `QUANLITY` char(2) DEFAULT NULL,
  `OPERDATE` datetime DEFAULT NULL,
  `IMAGEPATH` varchar(256) DEFAULT NULL,
  `BUSINESSTYPE` varchar(4) DEFAULT NULL,
  `BANKNO` varchar(20) DEFAULT NULL,
  `AGENCYNO` varchar(20) DEFAULT NULL,
  `BUSINESSID` bigint(30) DEFAULT NULL,
  `RESERVE1` varchar(50) DEFAULT NULL,
  `RESERVE2` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `IX_MONEYDATA_ATM_MON` (`MON`),
  KEY `IX_MONEYDATA_ATM_COLTIME` (`COLTIME`),
  KEY `IX_MONEYDATA_ATM_OPERDATE` (`OPERDATE`) USING BTREE,
  KEY `IX_MONEYDATA_ATM_BUSINESSID` (`BUSINESSID`) USING BTREE
) ENGINE=MyISAM AUTO_INCREMENT=14 DEFAULT CHARSET=utf8;

ALTER TABLE `MONEYDATA_ATM` ADD COLUMN  `ID` smallint(6) NOT NULL AUTO_INCREMENT;
ALTER TABLE `MONEYDATA_ATM` ADD COLUMN  `PERCODE` varchar(24) DEFAULT NULL;
ALTER TABLE `MONEYDATA_ATM` ADD COLUMN  `COLTIME` datetime DEFAULT NULL;
ALTER TABLE `MONEYDATA_ATM` ADD COLUMN  `MON` varchar(20) DEFAULT NULL;
ALTER TABLE `MONEYDATA_ATM` ADD COLUMN  `MONTYPE` char(3) DEFAULT NULL;
ALTER TABLE `MONEYDATA_ATM` ADD COLUMN  `MONVAL` decimal(8,2) DEFAULT NULL;
ALTER TABLE `MONEYDATA_ATM` ADD COLUMN  `MONVER` char(4) DEFAULT NULL;
ALTER TABLE `MONEYDATA_ATM` ADD COLUMN  `TRUEFLAG` char(1) DEFAULT NULL;
ALTER TABLE `MONEYDATA_ATM` ADD COLUMN  `QUANLITY` char(2) DEFAULT NULL;
ALTER TABLE `MONEYDATA_ATM` ADD COLUMN  `OPERDATE` datetime DEFAULT NULL;
ALTER TABLE `MONEYDATA_ATM` ADD COLUMN  `IMAGEPATH` varchar(256) DEFAULT NULL;
ALTER TABLE `MONEYDATA_ATM` ADD COLUMN  `BUSINESSTYPE` varchar(4) DEFAULT NULL;
ALTER TABLE `MONEYDATA_ATM` ADD COLUMN  `BANKNO` varchar(20) DEFAULT NULL;
ALTER TABLE `MONEYDATA_ATM` ADD COLUMN  `AGENCYNO` varchar(20) DEFAULT NULL;
ALTER TABLE `MONEYDATA_ATM` ADD COLUMN  `BUSINESSID` bigint(30) DEFAULT NULL;
ALTER TABLE `MONEYDATA_ATM` ADD COLUMN  `RESERVE1` varchar(50) DEFAULT NULL;
ALTER TABLE `MONEYDATA_ATM` ADD COLUMN  `RESERVE2` varchar(50) DEFAULT NULL;

CREATE TABLE  IF NOT EXISTS `DATECUT` (
  `ID` int(10) unsigned NOT NULL auto_increment,
  `LASTDATE` varchar(20) default NULL,
  `CURDATE` varchar(20) default NULL,
  `STATUS` int(1) default '0',
  `CUTTIME` int(6) default '0',
  `ENDTIME` int(6) default '0',
  PRIMARY KEY  (`ID`)
) ENGINE=MyISAM AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;

ALTER TABLE `DATECUT` ADD COLUMN   `ID` int(10) unsigned NOT NULL auto_increment;
ALTER TABLE `DATECUT` ADD COLUMN   `LASTDATE` varchar(20) default NULL;
ALTER TABLE `DATECUT` ADD COLUMN   `CURDATE` varchar(20) default NULL;
ALTER TABLE `DATECUT` ADD COLUMN   `STATUS` int(1) default '0';
ALTER TABLE `DATECUT` ADD COLUMN   `CUTTIME` int(6) default '0';
ALTER TABLE `DATECUT` ADD COLUMN   `ENDTIME` int(6) default '0';

CREATE TABLE  IF NOT EXISTS `ROUTE` (
  `ID` int(32) NOT NULL auto_increment,
  `TARGETBANK` varchar(20) default NULL,
  `FORWARDBANK` varchar(20) NOT NULL,
  `IPADDR` varchar(20) NOT NULL,
  `PORT_` varchar(8) default NULL,
  `USER_` varchar(20) NOT NULL,
  `PASSWORD_` varchar(20) NOT NULL,
  `LOCALDIR` varchar(100) NOT NULL,
  `REMOTEDIR` varchar(100) NOT NULL,
  `TYPE_` int(1) default NULL COMMENT '0:ftp上传1：ftp下载3:sftp上传4：sftp下载',
  `SERVICECODE` int(20) default NULL,
  `LASTDATE` varchar(20) default NULL,
  `STARTTIME` int(6) default NULL,
  `INTER_VAL` int(32) default NULL COMMENT '121212:12点12分12秒',
  `STATUS_` char(1) NOT NULL default '1',
  `MODEL_` int(1) NOT NULL default 0,
  PRIMARY KEY  (`ID`)
) ENGINE=MyISAM AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;


ALTER TABLE `ROUTE` ADD COLUMN  `ID` int(32) NOT NULL auto_increment;
ALTER TABLE `ROUTE` ADD COLUMN  `TARGETBANK` varchar(20) default NULL;
ALTER TABLE `ROUTE` ADD COLUMN  `FORWARDBANK` varchar(20) NOT NULL;
ALTER TABLE `ROUTE` ADD COLUMN  `IPADDR` varchar(20) NOT NULL;
ALTER TABLE `ROUTE` ADD COLUMN  `PORT_` varchar(8) default NULL;
ALTER TABLE `ROUTE` ADD COLUMN  `USER_` varchar(20) NOT NULL;
ALTER TABLE `ROUTE` ADD COLUMN  `PASSWORD_` varchar(20) NOT NULL;
ALTER TABLE `ROUTE` ADD COLUMN  `LOCALDIR` varchar(100) NOT NULL;
ALTER TABLE `ROUTE` ADD COLUMN  `REMOTEDIR` varchar(100) NOT NULL;
ALTER TABLE `ROUTE` ADD COLUMN  `TYPE_` int(1) default NULL COMMENT '0:上传1：下载';
ALTER TABLE `ROUTE` ADD COLUMN  `SERVICECODE` int(20) default NULL;
ALTER TABLE `ROUTE` ADD COLUMN  `LASTDATE` varchar(20) default NULL;
ALTER TABLE `ROUTE` ADD COLUMN  `STARTTIME` int(6) default NULL;
ALTER TABLE `ROUTE` ADD COLUMN  `INTER_VAL` int(32) default NULL COMMENT '121212:12点12分12秒';
ALTER TABLE `ROUTE` ADD COLUMN  `STATUS_` char(1) NOT NULL default '1';
ALTER TABLE `ROUTE` ADD COLUMN  `MODEL_` int(1) NOT NULL default 0;
  
CREATE TABLE  IF NOT EXISTS `ROUTERULE` (
  `ID` int(32) NOT NULL auto_increment,
  `ROUTEID` int(32) default NULL,
  `FILEEXTEND` varchar(10) default NULL,
  PRIMARY KEY  (`ID`)
) ENGINE=MyISAM AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

ALTER TABLE `ROUTERULE` ADD COLUMN   `ID` int(32) NOT NULL auto_increment;  
ALTER TABLE `ROUTERULE` ADD COLUMN    `ROUTEID` int(32) default NULL;       
ALTER TABLE `ROUTERULE` ADD COLUMN    `FILEEXTEND` varchar(10) default NULL;

ALTER TABLE `PERINFO` ADD COLUMN `TERMINALNO`  varchar(30) NULL ;